// @ts-check
const eslint = require('@eslint/js');
const tseslint = require('typescript-eslint');
const angular = require('angular-eslint');
const perfectionist = require('eslint-plugin-perfectionist');
const unusedImports = require('eslint-plugin-unused-imports');
const globals = require('globals');

module.exports = tseslint.config(
  {
    // Generated by `npm run api:generate` (openapi-ts.config.ts); never hand-edited.
    // The rest are build/native output, never source.
    ignores: [
      'src/core/api/generated/**',
      'www/**',
      'coverage/**',
      '.angular/**',
      'android/**',
      'ios/**',
    ],
  },
  {
    plugins: {
      'unused-imports': unusedImports,
    },
    rules: {
      'unused-imports/no-unused-imports': 'error',
      'unused-imports/no-unused-vars': [
        'warn',
        {
          vars: 'all',
          varsIgnorePattern: '^_',
          args: 'after-used',
          argsIgnorePattern: '^_',
        },
      ],
    },
  },
  {
    plugins: {
      perfectionist,
    },
    rules: {
      'perfectionist/sort-imports': [
        'error',
        {
          customGroups: [
            {
              groupName: 'angular',
              elementNamePattern: '@angular',
            },
          ],
          groups: [
            'type-import',
            'value-builtin',
            'angular',
            'value-external',
            'type-internal',
            'value-internal',
            ['type-parent', 'type-sibling', 'type-index'],
            ['value-parent', 'value-sibling', 'value-index'],
            'ts-equals-import',
            'unknown',
          ],
          newlinesBetween: 0,
          tsconfig: {
            rootDir: '.',
          },
        },
      ],
    },
  },
  {
    files: ['**/*.ts'],
    ignores: ['projects/**/*'],
    extends: [
      eslint.configs.recommended,
      ...tseslint.configs.recommended,
      ...tseslint.configs.stylistic,
      ...angular.configs.tsRecommended,
    ],
    processor: angular.processInlineTemplates,
    languageOptions: {
      globals: {
        ...globals.browser,
        ...globals.node,
      },
    },
    rules: {
      // Turn off no-unused-vars as it conflicts with unused-imports
      '@typescript-eslint/no-unused-vars': 'off',

      // Prefer "type" over "interface" for type definitions
      '@typescript-eslint/consistent-type-definitions': ['warn', 'type'],

      '@angular-eslint/component-class-suffix': [
        'error',
        { suffixes: ['Page', 'Component'] },
      ],
      '@angular-eslint/component-selector': [
        'error',
        { type: 'element', prefix: 'app', style: 'kebab-case' },
      ],
      '@angular-eslint/directive-selector': [
        'error',
        { type: 'attribute', prefix: 'app', style: 'camelCase' },
      ],
    },
  },
  {
    files: ['**/*.html'],
    extends: [
      ...angular.configs.templateRecommended,
      ...angular.configs.templateAccessibility,
    ],
    rules: {},
  },
  {
    files: ['**/*.spec.ts'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },
  {
    // src/core must stay framework-agnostic plain TypeScript so it can be
    // reused from a future Flutter or native port without a rewrite.
    files: ['src/core/**/*.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            '@angular/*',
            '@ionic/*',
            '@capacitor/*',
            'rxjs',
            'rxjs/*',
          ],
        },
      ],
    },
  },
  {
    // src/app must go through the @core/* alias, never reach into src/core
    // with a relative path, so the boundary stays visible at a glance.
    files: ['src/app/**/*.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['../**/core/**', '../**/core'],
              message:
                "Import from '@core/*' instead of a relative path into src/core.",
            },
          ],
        },
      ],
    },
  }
);
